<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    public $guarded = [];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($product){
            $product->slug = str_slug($product->title);
        });
    }

    public function category_product(){
        return $this->hasOne(Category::class);
    }
}
